# Generated by Django 5.2.17 on 2026-09-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.CharField(max_length=100, unique=True)),
                ("designer", models.CharField(blank=True, max_length=200)),
                ("metadata_source", models.CharField(blank=True, max_length=200)),
                ("uploader", models.CharField(blank=True, max_length=200)),
                ("primary_tag", models.CharField(blank=True, max_length=200)),
                ("when_created", models.CharField(blank=True, max_length=50)),
                ("when_uploaded", models.CharField(blank=True, max_length=50)),
                ("where_created", models.CharField(blank=True, max_length=200)),
                ("icon_geography", models.CharField(blank=True, max_length=200)),
                ("icon_description", models.TextField(blank=True)),
                ("icon_context", models.TextField(blank=True)),
                ("creation_context", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("changes_requested", "Changes Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "png_file",
                    models.FileField(blank=True, null=True, upload_to="icons/png/"),
                ),
                (
                    "svg_file",
                    models.FileField(blank=True, null=True, upload_to="icons/svg/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="icons", to="core.tag"
                    ),
                ),
            ],
        ),
    ]
